import 'package:flutter/material.dart';
import 'models.dart';
final List<Course> coursesData = [
  Course(
    id: 'dsa',
    name: 'DSA',
    fullName: 'Data Structures & Algorithms',
    icon: Icons.storage_rounded,
    gradientColors: [const Color(0xFF6C63FF), const Color(0xFFFF6584)],
    topics: [
      Topic(
        id: 'arrays',
        name: 'Arrays',
        totalQuestions: 15,
        completedQuestions: 15,
        quizTaken: true,
        score: 92,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'linked-lists',
        name: 'Linked Lists',
        totalQuestions: 12,
        completedQuestions: 8,
        quizTaken: true,
        score: 75,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'stacks-queues',
        name: 'Stacks & Queues',
        totalQuestions: 10,
        completedQuestions: 10,
        quizTaken: true,
        score: 88,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'trees',
        name: 'Trees',
        totalQuestions: 18,
        completedQuestions: 5,
        quizTaken: false,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'graphs',
        name: 'Graphs',
        totalQuestions: 15,
        completedQuestions: 0,
        quizTaken: false,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'sorting',
        name: 'Sorting Algorithms',
        totalQuestions: 12,
        completedQuestions: 12,
        quizTaken: true,
        score: 95,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'dp',
        name: 'Dynamic Programming',
        totalQuestions: 20,
        completedQuestions: 3,
        quizTaken: false,
        difficulty: 'Hard',
      ),
    ],
  ),
  Course(
    id: 'cn',
    name: 'CN',
    fullName: 'Computer Networks',
    icon: Icons.network_check_rounded,
    gradientColors: [const Color(0xFF00D4FF), const Color(0xFF0099CC)],
    topics: [
      Topic(
        id: 'osi-model',
        name: 'OSI Model',
        totalQuestions: 10,
        completedQuestions: 8,
        quizTaken: true,
        score: 80,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'tcp-ip',
        name: 'TCP/IP Protocol',
        totalQuestions: 12,
        completedQuestions: 6,
        quizTaken: false,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'routing',
        name: 'Routing Protocols',
        totalQuestions: 15,
        completedQuestions: 0,
        quizTaken: false,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'network-security',
        name: 'Network Security',
        totalQuestions: 14,
        completedQuestions: 2,
        quizTaken: false,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'http-https',
        name: 'HTTP/HTTPS',
        totalQuestions: 8,
        completedQuestions: 8,
        quizTaken: true,
        score: 100,
        difficulty: 'Easy',
      ),
    ],
  ),
  Course(
    id: 'os',
    name: 'OS',
    fullName: 'Operating Systems',
    icon: Icons.computer_rounded,
    gradientColors: [const Color(0xFFFF6584), const Color(0xFFFF8A5C)],
    topics: [
      Topic(
        id: 'process-mgmt',
        name: 'Process Management',
        totalQuestions: 12,
        completedQuestions: 10,
        quizTaken: true,
        score: 85,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'memory-mgmt',
        name: 'Memory Management',
        totalQuestions: 15,
        completedQuestions: 7,
        quizTaken: false,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'file-systems',
        name: 'File Systems',
        totalQuestions: 10,
        completedQuestions: 10,
        quizTaken: true,
        score: 90,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'deadlocks',
        name: 'Deadlocks',
        totalQuestions: 8,
        completedQuestions: 4,
        quizTaken: false,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'cpu-scheduling',
        name: 'CPU Scheduling',
        totalQuestions: 11,
        completedQuestions: 0,
        quizTaken: false,
        difficulty: 'Medium',
      ),
    ],
  ),
  Course(
    id: 'oop',
    name: 'OOP',
    fullName: 'Object Oriented Programming',
    icon: Icons.account_tree_rounded,
    gradientColors: [const Color(0xFF4CAF50), const Color(0xFF2E7D32)],
    topics: [
      Topic(
        id: 'classes-objects',
        name: 'Classes & Objects',
        totalQuestions: 10,
        completedQuestions: 10,
        quizTaken: true,
        score: 95,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'inheritance',
        name: 'Inheritance',
        totalQuestions: 12,
        completedQuestions: 8,
        quizTaken: true,
        score: 78,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'polymorphism',
        name: 'Polymorphism',
        totalQuestions: 14,
        completedQuestions: 5,
        quizTaken: false,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'encapsulation',
        name: 'Encapsulation',
        totalQuestions: 8,
        completedQuestions: 8,
        quizTaken: true,
        score: 100,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'abstraction',
        name: 'Abstraction',
        totalQuestions: 10,
        completedQuestions: 2,
        quizTaken: false,
        difficulty: 'Medium',
      ),
    ],
  ),
  Course(
    id: 'c',
    name: 'C',
    fullName: 'C Programming',
    icon: Icons.code_rounded,
    gradientColors: [const Color(0xFF5C6BC0), const Color(0xFF3949AB)],
    topics: [
      Topic(
        id: 'c-basics',
        name: 'Basics & Syntax',
        totalQuestions: 15,
        completedQuestions: 15,
        quizTaken: true,
        score: 88,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'pointers',
        name: 'Pointers',
        totalQuestions: 18,
        completedQuestions: 10,
        quizTaken: true,
        score: 72,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'structures',
        name: 'Structures',
        totalQuestions: 10,
        completedQuestions: 8,
        quizTaken: false,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'file-handling',
        name: 'File Handling',
        totalQuestions: 12,
        completedQuestions: 0,
        quizTaken: false,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'memory-mgmt-c',
        name: 'Memory Management',
        totalQuestions: 14,
        completedQuestions: 3,
        quizTaken: false,
        difficulty: 'Hard',
      ),
    ],
  ),
  Course(
    id: 'java',
    name: 'Java',
    fullName: 'Java Programming',
    icon: Icons.coffee_rounded,
    gradientColors: [const Color(0xFFFF5722), const Color(0xFFE64A19)],
    topics: [
      Topic(
        id: 'java-basics',
        name: 'Java Basics',
        totalQuestions: 12,
        completedQuestions: 12,
        quizTaken: true,
        score: 92,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'collections',
        name: 'Collections Framework',
        totalQuestions: 16,
        completedQuestions: 8,
        quizTaken: true,
        score: 81,
        difficulty: 'Medium',
      ),
      Topic(
        id: 'exception-handling',
        name: 'Exception Handling',
        totalQuestions: 10,
        completedQuestions: 10,
        quizTaken: true,
        score: 90,
        difficulty: 'Easy',
      ),
      Topic(
        id: 'multithreading',
        name: 'Multithreading',
        totalQuestions: 14,
        completedQuestions: 5,
        quizTaken: false,
        difficulty: 'Hard',
      ),
      Topic(
        id: 'jdbc',
        name: 'JDBC',
        totalQuestions: 12,
        completedQuestions: 0,
        quizTaken: false,
        difficulty: 'Medium',
      ),
    ],
  ),
];
